# -*- coding: utf-8 -*-
"""Manual Standardization (Z-score normalization).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d51KFtPxJi4gDpwhoYl3lndK73Gxlqbt
"""

# uploading zip
from google.colab import files
uploaded = files.upload()

# Extracting zip
import zipfile

with zipfile.ZipFile('mnist_test.csv.zip', 'r') as zip_ref:
    zip_ref.extractall()

file_path = "mnist_test.csv"

import pandas as pd
import math

# Load CSV
def load_csv(file_path):
    df = pd.read_csv(file_path)
    return df

# Mean
def compute_mean(column):
    total = 0
    n = len(column)

    for value in column.tolist():
        total += value

    return total / n

# Standard Deviation
def compute_std(column, mean):
    total = 0
    n = len(column)

    for value in column.tolist():
        total += (value - mean) ** 2

    variance = total / n
    return math.sqrt(variance)

# Standardize column
def standardize_column(column):
    mean = compute_mean(column)
    std = compute_std(column, mean)

    standardized_values = []

    for value in column.tolist():
        if std != 0:
            z = (value - mean) / std
        else:
            z = 0
        standardized_values.append(z)

    return standardized_values

# Standardize DataFrame
def standardize_dataframe(df):
    df_standardized = df.copy()

    for col in df.columns:
        if df[col].dtype in ['int64', 'float64']:
            df_standardized[col] = standardize_column(df[col])

    return df_standardized

# Main
if __name__ == "__main__":

    file_path = "mnist_test.csv"   # ✅ FIXED

    df = load_csv(file_path)

    print("Original DataFrame:")
    print(df.head())

    df_std = standardize_dataframe(df)

    print("\nStandardized DataFrame:")
    print(df_std.head())